### PR TITLE
Pinout Image and Readme.md additions

### PR DESCRIPTION
**Pull request by ITCMD**
I had to create a pinout guide for my own use, so I decided to make it and upload it. I also added a section to the readme to link to the w1btr.com site, in case you're interested in linking to it!

AIOC Pinout

I also updated wording, added progress such as automatic PTT, and added an authorized resellers section if you'd like to use it! :P

image

### CODE REVIEW

**Comment by skuep** [comment]
Thanks for the pull request, much appreciated! I will look into it, when I have some spare time.

`Does **not** support radio programming` It should, actually. Programming should not be affected by Virtual VOX (otherwise it's a bug).

Thanks also for the work on the images, they seem to be hosted on imgur, which I don't like. Anyway, since this is an open-source project, I would like to keep the "where to buy" section very small and light, so I am not sure such a big image is warranted. I may change this to just a list of shops/people selling AIOCs. ;-)

**Comment by ITCMD** [comment]
All sounds great. I have not tested the programming functionality in auto vox mode. I think when I had asked you stated it would not work, but it was an unclear question on my part so I can see where confusion could have leaked in haha. Happy to hear it should work. Ill talk more about vox preferredness in #19 

I totally understand on wanting a smaller section.

**Comment by ITCMD** [comment]
My pinout image may be incorrect based on this post
https://ham.stackexchange.com/questions/1891/whats-the-pinout-for-kenwood-2-5mm-trs-3-5-mm-trs-connector

**Comment by ITCMD** [comment]
Yeah, Im all messed up on this. Gonna have to study the specs to figure it out. The confusing bit for me is where programming data goes in and out.

**Comment by skuep** [comment]
I'm sorry for not having had time to work on this. Will promise something to happen next month :-)

**Comment by ITCMD** [comment]
No problem, needs to be updated soon anyways

**Comment by skuep** [comment]
I will close this pull request for now although I am still interested in a descriptive image. There will be a hardware revision 1.1 in the near future that has a split pad for PTT1/RX. When the new hardware revision will be released, I am going to make a new image/photo.

**Pull request closed without merging**
