### PR TITLE
 Solder guide on the PCB itself

### PR DESCRIPTION
**Pull request by rhgndf**
Here's how you can use the PCB as a solder guide. I have noticed that the TRS connectors have a small tab that can be used to align the connectors. I extended the PCB by 0.5mm and added an indent:

image

I have not measured it properly, but the indents are approximately the width of the tabs

### CODE REVIEW

**Comment by legonigel** [comment]
I'm going to express my disagreement with this: As someone who has soldered ~500 AIOCs, I find the spacing of the white spacer on the jacks to be highly inconsistent. For some units jacks, the tab on the TRS jack interferes with board as-is, while for other jacks it can be 2-3mm away. 

Since the connector spacing and parallelism is highly sensitive, I don't think this would work as well. Even a few mm of difference in connector spacing make the AIOC not fit in a radio, or pop-out, based on my experience with customer returns.

**Comment by skuep** [comment]
Let me first say, I am sorry you had to solder 500 of those. 😁 Holy moly, where did they all go? 

I am also on the fence for pretty much the same reasons. Those connectors have very coarse tolerances. Relevant for a good fit is not only the distance between them but also parallelity. I don't think you can achieve that sufficiently with this design using the white plastic body, unfortunately.

**Comment by WROG208** [comment]
I have been using pigtails instead of soldering the jacks to the AIOC. A lot easier and no need for a guide.

**Comment by rhgndf** [comment]
Thanks for all the feedback! In that case, it seems like a 3d printed solder guide, or a HT solder guide is better. Closing this PR.

**Pull request closed without merging**
