### PR TITLE
All-In-One-Cable for the truSDX Radio

### PR DESCRIPTION
**Pull request by skuep**
This pull request adds a new PCB version of the AIOC for connecting up a truSDX radio.
Connectors have been changed to 2x 3.5mm with a spacing of 13.5mm. Pinout was modified and some changes to the voltage levels were made.

Currently this design is untested and open for review.

### CODE REVIEW

**Comment by skuep** [comment]
Just to give a heads up on this, I produced a few beta boards for testing. But since I received some information about the "open-sourceness" of the truSDX project, I am very hesitant to support them with a custom truSDX-AIOC hardware version. Also there are rumors around, where the truSDX developer is looking into implementing the AIOC-functionality directly into the truSDX firmware, in which case the truSDX-AIOC would be obsolete.

Let me know what you think, if you don't agree with me. Contact me if you have a truSDX (with two TRS connectors spaced 12mm apart) and want a PCB for testing.

**Comment by skuep** [comment]
I am going to close this one, since there is a) no interest and b) the authors of the truSDX project seem to indicate that they want to add this functionality into their own firmware anyway.

**Comment by Nehem11e** [comment]
Looks like I was too late to this to try and help contribute/test. Is there an overview of the change in the circuit that was needed? Asked another way. Can the changes be done down stream or in the adapter cables? For example If I have a mainline board can I just add an adapter with some attenuation or were the circuitry changes more complicated than that?

**Comment by ecologito** [comment]
Thank you to all folks working no this neat project, i am not sure if I should make an adapter cable from the audio jacks or make anoth type of connector to plug this into my Radioshack htx10 radio. It would be great if I could try FT8 with this little radio knowin the pins:
image

**Pull request closed without merging**
