### PR TITLE
Use more common USB-C connector footprint & update to KiCad 8 w/ JLCPCB plugin

### PR DESCRIPTION
**Pull request by lexszero**
Connector in the original design was not available and have a rare footprint, so it was replace with another one with a more common footprint and plenty of alternative parts.

Fixes issue #65

### CODE REVIEW

**Comment by skuep** [comment]
Thank You for your pull request.
I am going to leave this idle for now, due to time constraints, but I will remember it when we will have supply chain problems again ;-)

**Comment by ValentinVoigt** [comment]
@lexszero I tried to order your newer version, but the alignment of the USB-C connector doesn't seem right to me.

chrome_hgS5mLGvGY

**Comment by lexszero** [comment]
> @lexszero I tried to order your newer version, but the alignment of the USB-C connector doesn't seem right to me.
> Edit: U1 seems to be wrongly oriented, too.

Yeah, I had similarly misaligned parts on preview when ordering, after quick chat with support they assured me that preview is not very accurate and their engineers will check and correct the design files in DFM before assembly. They were right, and it turned out to be fine, I have received perfectly working PCBs. It seems that KiCAD JLCPCB export plugin has bugs, or I'm doing something wrong (I'm not an expert in KiCAD and if you're choosing to proceed, you're doing it at your own risk).

image
image

**Comment by ValentinVoigt** [comment]
Thanks for getting back to me!

Yeah, I'm no expert either. I have yet to order a board that works first try. 😅 

I'm still undecided whether I want to submit a seemingly broken version, but I do think that this should not be merged yet. We should at least document this problem.

Really appreciate your work, especially since there are out-of-stock parts in the official version. Once there's a less sketchy version available, I'll be happy to give it a try.

**Comment by skuep** [comment]
In remember editing the USB socket in the current design due to this issue...

**Comment by rhgndf** [comment]
@lexszero The gerber file you provided has one small error. The solder paste is not aligned with the holes of the USB-C connector:

image

**Comment by rhgndf** [comment]
Apart from that everything seems working, have ordered 50 boards with your gerber.

One improvement that could be made is changing MHT192UGCT to 19-217/GHC-YR1S2/6T, which is an "Extended Part 👍" type according to https://jlcpcb.com/parts/basic_parts, which could reduce the extended component fee.

**Comment by skuep** [comment]
I took over your changes from this PR into PR https://github.com/skuep/AIOC/pull/93
Thanks a lot for the suggestion, I ultimately decided on the same GCT part

**Pull request closed without merging**
